name: rl
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python
  - jupyter
  - notebook
  - pandas
  - matplotlib
  - swig
  - torchaudio
  - pytorch
  - cudatoolkit=10.2
  - torchvision
  - urllib3
  - libgcc=5.2.0
  - libstdcxx-ng
  - pip:
    - pygame
